### ISSUE TITLE
Role argument validation fails when play skipped, due to a dependency on facts not gathered due to it being skipped

### ISSUE THREAD

**Issue by tomkivlin** [prometheus-community/ansible#289] opened 2024-02-09 16:04 UTC
I am using the [node_exporter](https://github.com/prometheus-community/ansible/tree/main/roles/node_exporter) role, which includes [role argument validation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation).  

Using tags to skip the inclusion of a particular play doesn't appear to stop the argument validation from taking place, which results in a failure as the role has a default var requiring gather_facts having run.  Using a tag to only run that particular playbook, or no tags at all, results in successful execution.

e.g.

```yaml
# site.yml
---
- name: Deploy common exporters
  hosts: monitored,monitoring-server
  vars_files:
    - ../vars/prometheus.yml
  roles:
    - prometheus.prometheus.node_exporter
  tags:
    - exporters

- name: Setup core monitoring software
  hosts: monitoring-server
  vars_files:
    - ../vars/prometheus.yml
  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.alertmanager
    - prometheus.prometheus.snmp_exporter
  tags:
    - prometheus
```

If I run the following commands, it works:

```bash
$ ansible-playbook -i inventory.yml site.yml --tags exporters
$
$ ansible-playbook -i inventory.yml site.yml
```

If I run the following, it fails:

```bash
$ ansible-playbook -i inventory.yml site.yml --tags prometheus
# output removed for brevity #
PLAY [Deploy common exporters] *************************************************************************************************************************************

TASK [prometheus.prometheus.node_exporter : Validating arguments against arg spec 'main' - Prometheus Node Exporter] ***********************************************
fatal: [srv1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined"}
fatal: [srv2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined"}
fatal: [monitoring-server]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined. {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}: 'ansible_architecture' is undefined. 'ansible_architecture' is undefined"}
```

This seems to be because the default vars for this role include a dependency on gather_facts having run on all the target hosts, as otherwise the variable `ansible_architecture` isn't created & set.

If I manually add the following to my own vars file, then it works as expected.  

```yaml
#../vars/prometheus.yml
ansible_architecture: x86_64
```

I don't know whether there is a way to disable the role argument validation in the case that a role is not called due to tags use, or whether this is a more fundamental bug (or feature) in Ansible.

**Comment by gardar** [comment] 2024-02-09 17:50
Interesting, it looks like it's ignoring the tag completely and running the exporters play regardless, it even prints the name of the play `Deploy common exporters`.
After you define the `ansible_architecture` variable does it continue with other tasks from that play or just jump over to the `Setup core monitoring software` play?

The task `Validating arguments against arg spec` is not something that's defined in the role and is something that ansible adds to every play where roles include argument specs: https://github.com/ansible/ansible/blob/a23ea2aef25a1256bc9850d42180351d5cd54619/lib/ansible/playbook/role/__init__.py#L61 and I don't see any options for disabling it.

I'm a bit surprised that this issue has not been raised before as I would have thought that this issue would affect many, the only discussion on the subject that I could find is this one: https://groups.google.com/g/ansible-project/c/h3StjZ75_MI

With that being said, it's strange that it doesn't recognize `ansible_architecture` as you don't seem to be disabling facts gathering in the playbook.
The `ansible_architecture` variable is used in the other roles as well so I would have thought that they would also fail the argument spec validation.

Have you tried using `--skip-tags: "exporters"` to see if that makes you truly skip the exporters play?
Also curious if you would run into the same issue by including the role at a task level instead of a play level with `ansible.builtin.include_role` since it doesn't include the role unless needed.

**Comment by gardar** [comment] 2024-02-09 19:52
Yes it looks like using `roles:` in the play is essentially the same as using `ansible.builtin.import_role` as it is being evaluated even though it is skipped because of the `--tags`
In addition it seems that the arg spec validation task that's injected before is not getting tagged as it should so that it runs that task no matter what.

IMHO this is a bug and can't be by design, I mean the facts gathering seems to be tagged correctly so that it doesn't run so why shouldn't the argument spec validation task be tagged as well.
At least this should be mentioned somewhere in the ansible docs.

**Comment by tomkivlin** [comment] 2024-02-09 21:41
Yes, agreed. I'll raise an issue in the ansible project.  Thanks for your help.

**Comment by tomkivlin** [comment] 2024-02-09 22:36
Raised an issue here: https://github.com/ansible/ansible/issues/82670

**Comment by gardar** [comment] 2024-03-08 21:38
Closing this since it's a feature/bug of ansible and out of scope for the collection.

**Closed** 2024-03-08 21:38 UTC
Labels: invalid
